- name: PiHole Setup
  hosts: localhost
  connection: local
  tasks:
    - name: Install prerequisite packages
      ansible.builtin.apt:
        pkg:
          - libffi-dev
          - libssl-dev
          - python3
          - python3-pip
          - apt-transport-https
        update_cache: yes
      become: true

    - name: Remove packages
      ansible.builtin.apt:
        pkg:
          - python-configparser
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
      become: true

    - name: Add keyring
      shell: |
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/raspbian/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add specified repository into sources list
      shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/raspbian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes
      become: true

    - name: create docker group
      ansible.builtin.group:
        name: docker
        gid: 1750
        state: present
      become: true

    - name: make pi user execute docker commands
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        group: docker
      become: true

    - name: add Tailscale to repos
      shell: |
        curl -fsSL https://pkgs.tailscale.com/stable/raspbian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
        curl -fsSL https://pkgs.tailscale.com/stable/raspbian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

    - name: Install Tailscale
      ansible.legacy.apt:
        name: tailscale
        state: present
        update_cache: yes
      become: true

    - name: Next Steps
      ansible.builtin.debug:
        msg: "restart your machine, run tailscale up --ssh, and then docker-compose up"
